begin;

/*
 * ==========================================================
 * CING WALLET — TOPUP PROMOTION + ADMIN REPORTING V1
 * ==========================================================
 *
 * Scope:
 *
 * 1. Current top-up promotion configuration.
 * 2. Threshold tiers.
 * 3. Immutable configuration history.
 * 4. Backend-only Wallet reporting.
 *
 * IMPORTANT:
 *
 * This migration DOES NOT modify the existing verified top-up
 * settlement authority.
 *
 * Therefore applying this migration cannot award promotion
 * money to any customer.
 *
 * Promotion is created disabled and with zero tiers.
 */


/* ==========================================================
 * 1. CURRENT PROMOTION CONFIG
 * ========================================================== */

create table
if not exists
public.cing_wallet_topup_promotion_config (
  id smallint primary key,

  enabled boolean
    not null
    default false,

  name text,

  starts_at timestamptz,

  ends_at timestamptz,

  updated_by text,

  created_at timestamptz
    not null
    default now(),

  updated_at timestamptz
    not null
    default now(),

  constraint
    cing_wallet_topup_promotion_config_singleton_ck
    check (id = 1),

  constraint
    cing_wallet_topup_promotion_config_window_ck
    check (
      starts_at is null
      or ends_at is null
      or ends_at > starts_at
    )
);

insert into
public.cing_wallet_topup_promotion_config (
  id,
  enabled,
  name,
  starts_at,
  ends_at,
  updated_by
)
values (
  1,
  false,
  null,
  null,
  null,
  null
)
on conflict (id)
do nothing;


/* ==========================================================
 * 2. PROMOTION TIERS
 *
 * min_topup_amount:
 * minimum real-money top-up amount required for the tier.
 *
 * bonus_amount:
 * additional Cing Wallet value credited by the promotion.
 *
 * Example semantics:
 *
 * min=1000000 bonus=200000
 * means top up >= 1,000,000 VND qualifies for +200,000.
 *
 * Later settlement authority will choose the highest qualified
 * min_topup_amount.
 * ========================================================== */

create table
if not exists
public.cing_wallet_topup_promotion_tiers (
  id uuid
    primary key
    default gen_random_uuid(),

  config_id smallint
    not null
    default 1
    references
      public.cing_wallet_topup_promotion_config(id)
    on delete restrict,

  min_topup_amount bigint
    not null,

  bonus_amount bigint
    not null,

  created_at timestamptz
    not null
    default now(),

  constraint
    cing_wallet_topup_promotion_tiers_config_ck
    check (config_id = 1),

  constraint
    cing_wallet_topup_promotion_tiers_min_ck
    check (min_topup_amount > 0),

  constraint
    cing_wallet_topup_promotion_tiers_bonus_ck
    check (bonus_amount > 0),

  constraint
    cing_wallet_topup_promotion_tiers_amount_uq
    unique (
      config_id,
      min_topup_amount
    )
);

create index
if not exists
cing_wallet_topup_promotion_tiers_lookup_idx
on public.cing_wallet_topup_promotion_tiers (
  config_id,
  min_topup_amount desc
);


/* ==========================================================
 * 3. IMMUTABLE CONFIGURATION HISTORY
 *
 * Every admin configuration mutation writes a complete JSONB
 * snapshot after the mutation.
 *
 * Nothing updates or deletes this audit history.
 * ========================================================== */

create table
if not exists
public.cing_wallet_topup_promotion_history (
  id bigint
    generated by default as identity
    primary key,

  action text
    not null,

  actor_id text,

  snapshot jsonb
    not null,

  created_at timestamptz
    not null
    default clock_timestamp(),

  constraint
    cing_wallet_topup_promotion_history_action_ck
    check (
      action in (
        'configure',
        'disable'
      )
    ),

  constraint
    cing_wallet_topup_promotion_history_snapshot_ck
    check (
      jsonb_typeof(snapshot) = 'object'
    )
);

create index
if not exists
cing_wallet_topup_promotion_history_created_idx
on public.cing_wallet_topup_promotion_history (
  created_at desc,
  id desc
);


/* ==========================================================
 * 4. ACL — TABLES ARE BACKEND READABLE, NOT DIRECTLY MUTABLE
 * ========================================================== */

revoke all
on table
public.cing_wallet_topup_promotion_config
from public, anon, authenticated, service_role;

grant select
on table
public.cing_wallet_topup_promotion_config
to service_role;


revoke all
on table
public.cing_wallet_topup_promotion_tiers
from public, anon, authenticated, service_role;

grant select
on table
public.cing_wallet_topup_promotion_tiers
to service_role;


revoke all
on table
public.cing_wallet_topup_promotion_history
from public, anon, authenticated, service_role;

grant select
on table
public.cing_wallet_topup_promotion_history
to service_role;


/* ==========================================================
 * 5. ADMIN CONFIGURATION AUTHORITY
 *
 * This RPC owns all writes to promotion configuration.
 *
 * p_tiers format:
 *
 * [
 *   {
 *     "min_topup_amount": 1000000,
 *     "bonus_amount": 200000
 *   }
 * ]
 *
 * No Wallet account or Wallet ledger is touched here.
 * ========================================================== */

create or replace function
public.cing_wallet_admin_configure_topup_promotion_v1(
  p_enabled boolean,
  p_name text,
  p_starts_at timestamptz,
  p_ends_at timestamptz,
  p_tiers jsonb,
  p_actor_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_enabled boolean :=
    coalesce(
      p_enabled,
      false
    );

  v_name text :=
    nullif(
      btrim(
        coalesce(
          p_name,
          ''
        )
      ),
      ''
    );

  v_actor_id text :=
    nullif(
      btrim(
        coalesce(
          p_actor_id,
          ''
        )
      ),
      ''
    );

  v_tiers jsonb :=
    coalesce(
      p_tiers,
      '[]'::jsonb
    );

  v_tier_count integer;

  v_snapshot jsonb;
begin

  if jsonb_typeof(v_tiers) <> 'array' then
    raise exception
      'CING_WALLET_PROMOTION_TIERS_INVALID'
      using errcode = '22023';
  end if;


  if p_starts_at is not null
     and p_ends_at is not null
     and p_ends_at <= p_starts_at
  then
    raise exception
      'CING_WALLET_PROMOTION_TIME_WINDOW_INVALID'
      using errcode = '22023';
  end if;


  /*
   * Serialize every admin edit.
   */
  perform 1
  from
    public.cing_wallet_topup_promotion_config
  where id = 1
  for update;

  if not found then
    raise exception
      'CING_WALLET_PROMOTION_CONFIG_MISSING'
      using errcode = '55000';
  end if;


  /*
   * Validate each JSON tier before deleting the previous set.
   */
  if exists (
    select 1
    from jsonb_array_elements(
      v_tiers
    ) item
    where
      jsonb_typeof(item) <> 'object'
      or not (
        item ? 'min_topup_amount'
      )
      or not (
        item ? 'bonus_amount'
      )
      or (
        item ->> 'min_topup_amount'
      ) !~ '^[0-9]+$'
      or (
        item ->> 'bonus_amount'
      ) !~ '^[0-9]+$'
      or (
        item ->> 'min_topup_amount'
      )::numeric <= 0
      or (
        item ->> 'bonus_amount'
      )::numeric <= 0
      or (
        item ->> 'min_topup_amount'
      )::numeric >
        9223372036854775807::numeric
      or (
        item ->> 'bonus_amount'
      )::numeric >
        9223372036854775807::numeric
  ) then
    raise exception
      'CING_WALLET_PROMOTION_TIER_INVALID'
      using errcode = '22023';
  end if;


  select count(*)
  into v_tier_count
  from jsonb_array_elements(
    v_tiers
  );


  if v_enabled
     and v_tier_count = 0
  then
    raise exception
      'CING_WALLET_PROMOTION_ENABLED_WITHOUT_TIERS'
      using errcode = '22023';
  end if;


  if (
    select count(*)
    from (
      select
        (
          item ->>
          'min_topup_amount'
        )::bigint
          as min_topup_amount
      from jsonb_array_elements(
        v_tiers
      ) item
      group by
        (
          item ->>
          'min_topup_amount'
        )::bigint
    ) distinct_tiers
  ) <> v_tier_count
  then
    raise exception
      'CING_WALLET_PROMOTION_TIER_DUPLICATE'
      using errcode = '22023';
  end if;


  /*
   * Replace current tier set atomically.
   */
  delete from
    public.cing_wallet_topup_promotion_tiers
  where config_id = 1;


  insert into
  public.cing_wallet_topup_promotion_tiers (
    config_id,
    min_topup_amount,
    bonus_amount
  )
  select
    1,
    (
      item ->>
      'min_topup_amount'
    )::bigint,

    (
      item ->>
      'bonus_amount'
    )::bigint

  from jsonb_array_elements(
    v_tiers
  ) item;


  update
    public.cing_wallet_topup_promotion_config
  set
    enabled =
      v_enabled,

    name =
      v_name,

    starts_at =
      p_starts_at,

    ends_at =
      p_ends_at,

    updated_by =
      v_actor_id,

    updated_at =
      clock_timestamp()

  where id = 1;


  select
    jsonb_build_object(
      'enabled',
        c.enabled,

      'name',
        c.name,

      'starts_at',
        c.starts_at,

      'ends_at',
        c.ends_at,

      'updated_by',
        c.updated_by,

      'updated_at',
        c.updated_at,

      'tiers',
        coalesce(
          (
            select jsonb_agg(
              jsonb_build_object(
                'min_topup_amount',
                  t.min_topup_amount,

                'bonus_amount',
                  t.bonus_amount
              )
              order by
                t.min_topup_amount
            )
            from
              public.cing_wallet_topup_promotion_tiers t
            where
              t.config_id = 1
          ),
          '[]'::jsonb
        )
    )
  into v_snapshot

  from
    public.cing_wallet_topup_promotion_config c

  where
    c.id = 1;


  insert into
  public.cing_wallet_topup_promotion_history (
    action,
    actor_id,
    snapshot
  )
  values (
    case
      when v_enabled
        then 'configure'
      else 'disable'
    end,

    v_actor_id,
    v_snapshot
  );


  return v_snapshot;

end;
$$;


/* ==========================================================
 * 6. CURRENT PROMOTION READ AUTHORITY
 * ========================================================== */

create or replace function
public.cing_wallet_get_topup_promotion_v1()
returns jsonb
language sql
security definer
set search_path = public
stable
as $$
  select
    jsonb_build_object(
      'enabled',
        c.enabled,

      'name',
        c.name,

      'starts_at',
        c.starts_at,

      'ends_at',
        c.ends_at,

      'updated_at',
        c.updated_at,

      'tiers',
        coalesce(
          (
            select jsonb_agg(
              jsonb_build_object(
                'min_topup_amount',
                  t.min_topup_amount,

                'bonus_amount',
                  t.bonus_amount
              )
              order by
                t.min_topup_amount
            )
            from
              public.cing_wallet_topup_promotion_tiers t
            where
              t.config_id = 1
          ),
          '[]'::jsonb
        )
    )
  from
    public.cing_wallet_topup_promotion_config c
  where
    c.id = 1;
$$;


/* ==========================================================
 * 7. ADMIN WALLET REPORTING
 *
 * Period metrics:
 * - real-money top-up
 * - promotion bonus
 * - Wallet spending
 * - refunds / reversals
 * - admin adjustment net
 *
 * Current liability:
 * - current account count
 * - current total Wallet balance
 *
 * Reports never mutate financial state.
 * ========================================================== */

create or replace function
public.cing_wallet_admin_summary_v1(
  p_from timestamptz,
  p_to timestamptz
)
returns jsonb
language plpgsql
security definer
set search_path = public
stable
as $$
declare
  v_from timestamptz :=
    p_from;

  v_to timestamptz :=
    p_to;

  v_result jsonb;
begin

  if v_from is not null
     and v_to is not null
     and v_to <= v_from
  then
    raise exception
      'CING_WALLET_REPORT_TIME_RANGE_INVALID'
      using errcode = '22023';
  end if;


  select jsonb_build_object(

    'period',
      jsonb_build_object(
        'from',
          v_from,

        'to',
          v_to
      ),

    'current',
      jsonb_build_object(
        'account_count',
          (
            select count(*)
            from
              public.cing_wallet_accounts
          ),

        'total_wallet_balance',
          (
            select
              coalesce(
                sum(balance),
                0
              )
            from
              public.cing_wallet_accounts
          )
      ),

    'period_totals',
      jsonb_build_object(

        'real_money_topup',
          (
            select
              coalesce(
                sum(amount),
                0
              )
            from
              public.cing_wallet_transactions wt
            where
              wt.transaction_type =
                'topup'
              and (
                v_from is null
                or wt.created_at >=
                  v_from
              )
              and (
                v_to is null
                or wt.created_at <
                  v_to
              )
          ),

        'promotion_bonus',
          (
            select
              coalesce(
                sum(amount),
                0
              )
            from
              public.cing_wallet_transactions wt
            where
              wt.transaction_type =
                'topup_promotion'
              and (
                v_from is null
                or wt.created_at >=
                  v_from
              )
              and (
                v_to is null
                or wt.created_at <
                  v_to
              )
          ),

        'wallet_spending',
          (
            select
              coalesce(
                sum(-amount),
                0
              )
            from
              public.cing_wallet_transactions wt
            where
              wt.transaction_type =
                'payment'
              and (
                v_from is null
                or wt.created_at >=
                  v_from
              )
              and (
                v_to is null
                or wt.created_at <
                  v_to
              )
          ),

        'refunds',
          (
            select
              coalesce(
                sum(amount),
                0
              )
            from
              public.cing_wallet_transactions wt
            where
              wt.transaction_type =
                'refund'
              and (
                v_from is null
                or wt.created_at >=
                  v_from
              )
              and (
                v_to is null
                or wt.created_at <
                  v_to
              )
          ),

        'reversals',
          (
            select
              coalesce(
                sum(amount),
                0
              )
            from
              public.cing_wallet_transactions wt
            where
              wt.transaction_type =
                'reversal'
              and (
                v_from is null
                or wt.created_at >=
                  v_from
              )
              and (
                v_to is null
                or wt.created_at <
                  v_to
              )
          ),

        'admin_adjustment_net',
          (
            select
              coalesce(
                sum(amount),
                0
              )
            from
              public.cing_wallet_transactions wt
            where
              wt.transaction_type =
                'admin_adjustment'
              and (
                v_from is null
                or wt.created_at >=
                  v_from
              )
              and (
                v_to is null
                or wt.created_at <
                  v_to
              )
          ),

        'transaction_count',
          (
            select
              count(*)
            from
              public.cing_wallet_transactions wt
            where
              (
                v_from is null
                or wt.created_at >=
                  v_from
              )
              and (
                v_to is null
                or wt.created_at <
                  v_to
              )
          )
      )
  )
  into v_result;


  return v_result;

end;
$$;


/* ==========================================================
 * 8. FUNCTION ACL
 * ========================================================== */

revoke all
on function
public.cing_wallet_admin_configure_topup_promotion_v1(
  boolean,
  text,
  timestamptz,
  timestamptz,
  jsonb,
  text
)
from public, anon, authenticated;

grant execute
on function
public.cing_wallet_admin_configure_topup_promotion_v1(
  boolean,
  text,
  timestamptz,
  timestamptz,
  jsonb,
  text
)
to service_role;


revoke all
on function
public.cing_wallet_get_topup_promotion_v1()
from public, anon, authenticated;

grant execute
on function
public.cing_wallet_get_topup_promotion_v1()
to service_role;


revoke all
on function
public.cing_wallet_admin_summary_v1(
  timestamptz,
  timestamptz
)
from public, anon, authenticated;

grant execute
on function
public.cing_wallet_admin_summary_v1(
  timestamptz,
  timestamptz
)
to service_role;


/* ==========================================================
 * 9. STRUCTURAL SAFETY ASSERTIONS
 * ========================================================== */

do $migration$
begin

  if not exists (
    select 1
    from
      public.cing_wallet_topup_promotion_config
    where
      id = 1
      and enabled = false
  ) then
    raise exception
      'CING_WALLET_PROMOTION_SAFE_DEFAULT_MISSING';
  end if;


  if exists (
    select 1
    from
      public.cing_wallet_topup_promotion_tiers
  ) then
    raise exception
      'CING_WALLET_PROMOTION_UNEXPECTED_INITIAL_TIERS';
  end if;


  /*
   * This foundation must not replace or redefine the live
   * top-up settlement function.
   */
  if to_regprocedure(
    'public.cing_wallet_settle_verified_topup_atomic(bigint)'
  ) is null
  then
    raise exception
      'CING_WALLET_EXISTING_TOPUP_AUTHORITY_MISSING';
  end if;

end;
$migration$;


commit;
