begin;

/*
 * CING GAME CENTER V2
 * OFFLINE REVIVAL SESSION EVENTS V1
 *
 * Depends on:
 * - revive credit foundation
 * - offline revive session foundation
 *
 * Every transition has a durable idempotency key.
 * This ledger is NOT the revive-credit ledger.
 *
 * No session creation or balance mutation here.
 */

create table public.cing_offline_revive_events (

  id bigint
    generated by default as identity
    primary key,

  session_id uuid not null
    references public.cing_offline_revive_sessions(id),

  user_id text not null,

  request_id uuid not null,

  event_seq integer not null,

  event_type text not null,

  pending_reason text,

  revive_index integer,

  credit_cost integer,

  credit_transaction_id bigint
    references public.cing_revive_credit_transactions(id),

  created_at timestamptz not null default now(),

  constraint cing_offline_revive_event_user_ck
    check (btrim(user_id) <> ''),

  constraint cing_offline_revive_event_seq_ck
    check (event_seq > 0),

  constraint cing_offline_revive_event_type_ck
    check (
      event_type in (
        'revive_pending',
        'revived',
        'finalized'
      )
    ),

  constraint cing_offline_revive_event_reason_ck
    check (
      pending_reason is null
      or pending_reason in ('timeout', 'death')
    ),

  constraint cing_offline_revive_event_payload_ck
    check (
      (
        event_type = 'revive_pending'
        and pending_reason is not null
        and revive_index is null
        and credit_cost is null
        and credit_transaction_id is null
      )
      or
      (
        event_type = 'revived'
        and pending_reason is null
        and revive_index between 1 and 5
        and credit_cost = (
          case revive_index
            when 1 then 1
            when 2 then 2
            when 3 then 4
            when 4 then 8
            when 5 then 16
          end
        )
        and credit_transaction_id is not null
      )
      or
      (
        event_type = 'finalized'
        and pending_reason is null
        and revive_index is null
        and credit_cost is null
        and credit_transaction_id is null
      )
    ),

  constraint cing_offline_revive_event_request_uq
    unique (user_id, request_id),

  constraint cing_offline_revive_event_sequence_uq
    unique (session_id, event_seq),

  constraint cing_offline_revive_event_credit_tx_uq
    unique (credit_transaction_id)

);

create index
  cing_offline_revive_events_session_history_idx
on public.cing_offline_revive_events (
  session_id,
  event_seq
);

create index
  cing_offline_revive_events_user_history_idx
on public.cing_offline_revive_events (
  user_id,
  created_at desc,
  id desc
);

/*
 * Business RPCs own every event insertion.
 * Even service_role cannot directly manufacture
 * a revival event.
 */

revoke all
on table public.cing_offline_revive_events
from public, anon, authenticated, service_role;

grant select
on table public.cing_offline_revive_events
to service_role;

commit;
