begin;

/*
 * ==========================================================
 * CING COMMERCE — POST-ORDER EFFECT AUTHORITY V1
 * ==========================================================
 *
 * Purpose:
 * provide durable, per-order, per-effect execution authority
 * for business effects that happen after canonical commerce
 * order creation.
 *
 * This migration intentionally does NOT switch the production
 * processor yet.
 *
 * Core guarantees:
 * - one durable row per (order_id, effect_key)
 * - PostgreSQL owns claim / lease / retry state
 * - concurrent workers cannot own the same live lease
 * - completed effects are immutable terminal successes
 * - failed / abandoned execution can be reclaimed
 * - Node/Redis are orchestration/optimization only
 */

create table if not exists
public.cing_commerce_order_effects (
  id bigint generated by default as identity primary key,

  order_id bigint not null
    references public.orders(id)
    on delete restrict,

  effect_key text not null,

  status text not null
    default 'pending',

  attempt_count integer not null
    default 0,

  claim_token uuid,

  claimed_at timestamptz,

  lease_expires_at timestamptz,

  completed_at timestamptz,

  last_error text,

  created_at timestamptz not null
    default now(),

  updated_at timestamptz not null
    default now(),

  constraint
    cing_commerce_order_effects_effect_key_ck
    check (
      effect_key in (
        'ipos_delivery',
        'game_plays',
        'daily_mission',
        'partner_spending',
        'local_spending',
        'points_deduct',
        'points_earn'
      )
    ),

  constraint
    cing_commerce_order_effects_status_ck
    check (
      status in (
        'pending',
        'processing',
        'completed',
        'failed'
      )
    ),

  constraint
    cing_commerce_order_effects_attempt_count_ck
    check (
      attempt_count >= 0
    ),

  constraint
    cing_commerce_order_effects_processing_ck
    check (
      (
        status = 'processing'
        and claim_token is not null
        and claimed_at is not null
        and lease_expires_at is not null
        and completed_at is null
      )
      or
      (
        status <> 'processing'
        and claim_token is null
        and claimed_at is null
        and lease_expires_at is null
      )
    ),

  constraint
    cing_commerce_order_effects_completed_ck
    check (
      (
        status = 'completed'
        and completed_at is not null
      )
      or
      (
        status <> 'completed'
        and completed_at is null
      )
    )
);

create unique index if not exists
cing_commerce_order_effects_order_effect_uq
on public.cing_commerce_order_effects (
  order_id,
  effect_key
);

create index if not exists
cing_commerce_order_effects_retry_idx
on public.cing_commerce_order_effects (
  status,
  lease_expires_at,
  updated_at
);

revoke all
on public.cing_commerce_order_effects
from public, anon, authenticated;

grant select
on public.cing_commerce_order_effects
to service_role;


/*
 * ----------------------------------------------------------
 * Ensure one effect row exists.
 * ----------------------------------------------------------
 *
 * Safe under concurrent insertion because the durable UNIQUE
 * constraint owns idempotency.
 */
create or replace function
public.cing_commerce_ensure_order_effect_v1(
  p_order_id bigint,
  p_effect_key text
)
returns public.cing_commerce_order_effects
language plpgsql
security definer
set search_path = public
as $$
declare
  v_effect
    public.cing_commerce_order_effects%rowtype;
begin
  if p_order_id is null then
    raise exception
      'COMMERCE_EFFECT_ORDER_ID_REQUIRED'
      using errcode = '22023';
  end if;

  if p_effect_key is null
     or btrim(p_effect_key) = '' then
    raise exception
      'COMMERCE_EFFECT_KEY_REQUIRED'
      using errcode = '22023';
  end if;

  if not exists (
    select 1
    from public.orders
    where id = p_order_id
  ) then
    raise exception
      'COMMERCE_EFFECT_ORDER_NOT_FOUND'
      using errcode = 'P0002';
  end if;

  insert into
    public.cing_commerce_order_effects (
      order_id,
      effect_key
    )
  values (
    p_order_id,
    p_effect_key
  )
  on conflict (
    order_id,
    effect_key
  )
  do nothing;

  select *
  into v_effect
  from public.cing_commerce_order_effects
  where order_id = p_order_id
    and effect_key = p_effect_key;

  return v_effect;
end;
$$;


/*
 * ----------------------------------------------------------
 * Claim / reclaim one effect.
 * ----------------------------------------------------------
 */
create or replace function
public.cing_commerce_claim_order_effect_v1(
  p_order_id bigint,
  p_effect_key text,
  p_lease_seconds integer default 120
)
returns table (
  effect_id bigint,
  order_id bigint,
  effect_key text,
  status text,
  attempt_count integer,
  claim_token uuid,
  lease_expires_at timestamptz,
  completed_at timestamptz,
  acquired boolean
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_effect
    public.cing_commerce_order_effects%rowtype;

  v_now timestamptz :=
    clock_timestamp();

  v_token uuid;
begin
  if p_lease_seconds is null
     or p_lease_seconds < 1
     or p_lease_seconds > 3600 then
    raise exception
      'COMMERCE_EFFECT_LEASE_INVALID'
      using errcode = '22023';
  end if;

  perform
    public.cing_commerce_ensure_order_effect_v1(
      p_order_id,
      p_effect_key
    );

  select e.*
  into v_effect
  from public.cing_commerce_order_effects e
  where e.order_id = p_order_id
    and e.effect_key = p_effect_key
  for update;

  if v_effect.status = 'completed' then
    return query
    select
      v_effect.id,
      v_effect.order_id,
      v_effect.effect_key,
      v_effect.status,
      v_effect.attempt_count,
      v_effect.claim_token,
      v_effect.lease_expires_at,
      v_effect.completed_at,
      false;

    return;
  end if;

  if v_effect.status = 'processing'
     and v_effect.lease_expires_at > v_now then
    return query
    select
      v_effect.id,
      v_effect.order_id,
      v_effect.effect_key,
      v_effect.status,
      v_effect.attempt_count,
      v_effect.claim_token,
      v_effect.lease_expires_at,
      v_effect.completed_at,
      false;

    return;
  end if;

  v_token :=
    gen_random_uuid();

  update
    public.cing_commerce_order_effects e
  set
    status = 'processing',
    attempt_count =
      e.attempt_count + 1,
    claim_token =
      v_token,
    claimed_at =
      v_now,
    lease_expires_at =
      v_now
      + make_interval(
          secs => p_lease_seconds
        ),
    completed_at =
      null,
    last_error =
      null,
    updated_at =
      v_now
  where e.id = v_effect.id
  returning e.*
  into v_effect;

  return query
  select
    v_effect.id,
    v_effect.order_id,
    v_effect.effect_key,
    v_effect.status,
    v_effect.attempt_count,
    v_effect.claim_token,
    v_effect.lease_expires_at,
    v_effect.completed_at,
    true;
end;
$$;

/*
 * ----------------------------------------------------------
 * Complete effect.
 *
 * Exact claim token is mandatory. A stale worker cannot mark
 * a reclaimed effect completed.
 * ----------------------------------------------------------
 */
create or replace function
public.cing_commerce_complete_order_effect_v1(
  p_order_id bigint,
  p_effect_key text,
  p_claim_token uuid
)
returns public.cing_commerce_order_effects
language plpgsql
security definer
set search_path = public
as $$
declare
  v_effect
    public.cing_commerce_order_effects%rowtype;

  v_now timestamptz :=
    clock_timestamp();
begin
  if p_claim_token is null then
    raise exception
      'COMMERCE_EFFECT_CLAIM_TOKEN_REQUIRED'
      using errcode = '22023';
  end if;

  select *
  into v_effect
  from public.cing_commerce_order_effects
  where order_id = p_order_id
    and effect_key = p_effect_key
  for update;

  if not found then
    raise exception
      'COMMERCE_EFFECT_NOT_FOUND'
      using errcode = 'P0002';
  end if;

  if v_effect.status = 'completed' then
    return v_effect;
  end if;

  if v_effect.status <> 'processing'
     or v_effect.claim_token
        is distinct from p_claim_token then
    raise exception
      'COMMERCE_EFFECT_CLAIM_MISMATCH'
      using errcode = '55000';
  end if;

  update
    public.cing_commerce_order_effects
  set
    status = 'completed',
    claim_token = null,
    claimed_at = null,
    lease_expires_at = null,
    completed_at = v_now,
    last_error = null,
    updated_at = v_now
  where id = v_effect.id
  returning *
  into v_effect;

  return v_effect;
end;
$$;


/*
 * ----------------------------------------------------------
 * Fail effect.
 *
 * Failure is retryable. Future claim may reclaim it.
 * ----------------------------------------------------------
 */
create or replace function
public.cing_commerce_fail_order_effect_v1(
  p_order_id bigint,
  p_effect_key text,
  p_claim_token uuid,
  p_error text
)
returns public.cing_commerce_order_effects
language plpgsql
security definer
set search_path = public
as $$
declare
  v_effect
    public.cing_commerce_order_effects%rowtype;

  v_now timestamptz :=
    clock_timestamp();
begin
  if p_claim_token is null then
    raise exception
      'COMMERCE_EFFECT_CLAIM_TOKEN_REQUIRED'
      using errcode = '22023';
  end if;

  select *
  into v_effect
  from public.cing_commerce_order_effects
  where order_id = p_order_id
    and effect_key = p_effect_key
  for update;

  if not found then
    raise exception
      'COMMERCE_EFFECT_NOT_FOUND'
      using errcode = 'P0002';
  end if;

  if v_effect.status = 'completed' then
    return v_effect;
  end if;

  if v_effect.status <> 'processing'
     or v_effect.claim_token
        is distinct from p_claim_token then
    raise exception
      'COMMERCE_EFFECT_CLAIM_MISMATCH'
      using errcode = '55000';
  end if;

  update
    public.cing_commerce_order_effects
  set
    status = 'failed',
    claim_token = null,
    claimed_at = null,
    lease_expires_at = null,
    completed_at = null,
    last_error =
      left(
        coalesce(
          nullif(
            btrim(p_error),
            ''
          ),
          'unknown_error'
        ),
        4000
      ),
    updated_at = v_now
  where id = v_effect.id
  returning *
  into v_effect;

  return v_effect;
end;
$$;


/*
 * Backend orchestration may invoke only the bounded lifecycle
 * functions. Direct table mutation remains forbidden.
 */
revoke all
on function
public.cing_commerce_ensure_order_effect_v1(
  bigint,
  text
)
from public, anon, authenticated;

revoke all
on function
public.cing_commerce_claim_order_effect_v1(
  bigint,
  text,
  integer
)
from public, anon, authenticated;

revoke all
on function
public.cing_commerce_complete_order_effect_v1(
  bigint,
  text,
  uuid
)
from public, anon, authenticated;

revoke all
on function
public.cing_commerce_fail_order_effect_v1(
  bigint,
  text,
  uuid,
  text
)
from public, anon, authenticated;

grant execute
on function
public.cing_commerce_ensure_order_effect_v1(
  bigint,
  text
)
to service_role;

grant execute
on function
public.cing_commerce_claim_order_effect_v1(
  bigint,
  text,
  integer
)
to service_role;

grant execute
on function
public.cing_commerce_complete_order_effect_v1(
  bigint,
  text,
  uuid
)
to service_role;

grant execute
on function
public.cing_commerce_fail_order_effect_v1(
  bigint,
  text,
  uuid,
  text
)
to service_role;


/*
 * Migration-time invariants.
 */
do $migration$
begin
  if not exists (
    select 1
    from pg_indexes
    where schemaname = 'public'
      and tablename =
        'cing_commerce_order_effects'
      and indexname =
        'cing_commerce_order_effects_order_effect_uq'
  ) then
    raise exception
      'COMMERCE_EFFECT_UNIQUENESS_MISSING';
  end if;
end;
$migration$;


/*
 * ==========================================================
 * ORDER-SPEND GAME PLAY AWARD AUTHORITY V1
 * ==========================================================
 *
 * Reuses public.game_play_transactions as the authoritative
 * game-play ledger.
 *
 * One commerce order may award game plays at most once.
 *
 * Atomic PostgreSQL transaction owns:
 *
 *   players.game_plays
 *   players.plays_from_spend
 *   game_play_transactions
 *   analytics_events compatibility projection
 *
 * Node check-before-write is not authority.
 */


/*
 * Durable reference fence for non-session game-play mutations.
 *
 * Existing integration-test cleanup rows remain compatible.
 * The uniqueness scope is intentionally limited to
 * order_spending.
 */
create unique index if not exists
game_play_transactions_order_spending_uq
on public.game_play_transactions (
  reference_type,
  reference_id
)
where
  reference_type = 'order_spending'
  and reference_id is not null;


/*
 * Commerce order-spend award.
 *
 * Caller supplies only canonical commerce order identity.
 * User, amount and threshold are resolved inside PostgreSQL.
 */
create or replace function
public.cing_commerce_award_order_spend_plays_v1(
  p_order_id bigint
)
returns table (
  order_id bigint,
  user_id text,
  order_code text,
  order_amount bigint,
  spend_per_play bigint,
  plays_awarded integer,
  balance_before integer,
  balance_after integer,
  plays_from_spend_after integer,
  replayed boolean
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order
    public.orders%rowtype;

  v_player
    public.players%rowtype;

  v_existing
    public.game_play_transactions%rowtype;

  v_spend_per_play bigint;

  v_amount bigint;

  v_plays integer;

  v_before integer;

  v_after integer;

  v_from_spend_after integer;

  v_user_id text;

  v_now timestamptz :=
    clock_timestamp();

  v_reference_id text;
begin
  if p_order_id is null then
    raise exception
      'COMMERCE_ORDER_ID_REQUIRED'
      using errcode = '22023';
  end if;


  /*
   * Canonical durable commerce order is authoritative.
   */
  select o.*
  into v_order
  from public.orders o
  where o.id = p_order_id
  for update;

  if not found then
    raise exception
      'COMMERCE_ORDER_NOT_FOUND'
      using errcode = 'P0002';
  end if;


  if v_order.payment_status <> 'paid' then
    raise exception
      'COMMERCE_ORDER_NOT_PAID'
      using errcode = '55000';
  end if;


  if v_order.payment_transaction_id is null then
    raise exception
      'COMMERCE_ORDER_PAYMENT_LINK_REQUIRED'
      using errcode = '55000';
  end if;


  /*
   * Payment projection must point back to this exact order.
   */
  if not exists (
    select 1
    from public.payment_transactions p
    where p.id =
      v_order.payment_transaction_id
      and p.order_created is true
      and p.order_id =
        v_order.id
      and p.payment_status = 'paid'
      and p.payment_purpose = 'order'
  ) then
    raise exception
      'COMMERCE_ORDER_PAYMENT_AUTHORITY_INVALID'
      using errcode = '55000';
  end if;


  v_user_id :=
    btrim(
      coalesce(
        nullif(v_order.user_id, ''),
        nullif(v_order.customer_phone, ''),
        ''
      )
    );

  if v_user_id = '' then
    raise exception
      'COMMERCE_ORDER_USER_REQUIRED'
      using errcode = '55000';
  end if;


  v_reference_id :=
    v_order.id::text;


  /*
   * Durable idempotent replay before any balance mutation.
   */
  select t.*
  into v_existing
  from public.game_play_transactions t
  where t.reference_type =
      'order_spending'
    and t.reference_id =
      v_reference_id;

  if found then
    if
      v_existing.user_id <>
        v_user_id
      or v_existing.transaction_type <>
        'add'
      or v_existing.amount <= 0
      or v_existing.balance_after <>
        v_existing.balance_before
        + v_existing.amount
    then
      raise exception
        'COMMERCE_ORDER_SPEND_PLAY_REPLAY_CONFLICT'
        using errcode = '55000';
    end if;

    return query
    select
      v_order.id,
      v_user_id,
      v_order.order_code,
      greatest(
        coalesce(
          v_order.subtotal,
          0
        ),
        0
      )::bigint,
      coalesce(
        nullif(
          (
            v_existing.metadata
              ->> 'spend_per_play'
          )::bigint,
          0
        ),
        0
      ),
      v_existing.amount,
      v_existing.balance_before,
      v_existing.balance_after,
      coalesce(
        (
          v_existing.metadata
            ->> 'plays_from_spend_after'
        )::integer,
        0
      ),
      true;

    return;
  end if;


  /*
   * Preserve existing production semantics:
   * spend reward excludes shipping whenever subtotal exists.
   */
  v_amount :=
    case
      when coalesce(
        v_order.subtotal,
        0
      ) > 0
      then v_order.subtotal::bigint

      else greatest(
        coalesce(
          v_order.total_amount,
          0
        )
        -
        coalesce(
          v_order.shipping_fee,
          0
        ),
        0
      )::bigint
    end;


  if v_amount <= 0 then
    /*
     * Zero-award orders need no balance mutation. They are not
     * inserted into game_play_transactions because that ledger
     * explicitly forbids amount = 0.
     */
    return query
    select
      v_order.id,
      v_user_id,
      v_order.order_code,
      v_amount,
      0::bigint,
      0,
      0,
      0,
      0,
      false;

    return;
  end if;


  select
    coalesce(
      nullif(
        c.spend_per_play,
        0
      ),
      20000
    )::bigint
  into v_spend_per_play
  from public.app_configs c
  where c.id = 1;

  if
    v_spend_per_play is null
    or v_spend_per_play <= 0
  then
    raise exception
      'COMMERCE_SPEND_PER_PLAY_INVALID'
      using errcode = '55000';
  end if;


  v_plays :=
    floor(
      v_amount::numeric
      /
      v_spend_per_play::numeric
    )::integer;


  if v_plays <= 0 then
    return query
    select
      v_order.id,
      v_user_id,
      v_order.order_code,
      v_amount,
      v_spend_per_play,
      0,
      0,
      0,
      0,
      false;

    return;
  end if;


  /*
   * Player row lock serializes all commerce-award mutation for
   * this user.
   */
  select p.*
  into v_player
  from public.players p
  where p.user_id =
    v_user_id
  for update;

  if not found then
    raise exception
      'PLAYER_NOT_FOUND'
      using errcode = 'P0002';
  end if;


  /*
   * Recheck idempotency AFTER player lock. A concurrent request
   * may have passed the optimistic replay check before waiting.
   */
  select t.*
  into v_existing
  from public.game_play_transactions t
  where t.reference_type =
      'order_spending'
    and t.reference_id =
      v_reference_id;

  if found then
    return query
    select
      v_order.id,
      v_user_id,
      v_order.order_code,
      v_amount,
      coalesce(
        (
          v_existing.metadata
            ->> 'spend_per_play'
        )::bigint,
        v_spend_per_play
      ),
      v_existing.amount,
      v_existing.balance_before,
      v_existing.balance_after,
      coalesce(
        (
          v_existing.metadata
            ->> 'plays_from_spend_after'
        )::integer,
        coalesce(
          v_player.plays_from_spend,
          0
        )
      ),
      true;

    return;
  end if;


  v_before :=
    coalesce(
      v_player.game_plays,
      0
    );

  update public.players p
  set
    game_plays =
      coalesce(
        p.game_plays,
        0
      )
      + v_plays,

    plays_from_spend =
      coalesce(
        p.plays_from_spend,
        0
      )
      + v_plays,

    updated_at =
      v_now

  where p.user_id =
    v_user_id

  returning
    p.game_plays,
    p.plays_from_spend

  into
    v_after,
    v_from_spend_after;


  if v_after <>
    v_before + v_plays
  then
    raise exception
      'COMMERCE_ORDER_SPEND_PLAY_BALANCE_INVARIANT'
      using errcode = '55000';
  end if;


  insert into
  public.game_play_transactions (
    user_id,
    transaction_type,
    amount,
    balance_before,
    balance_after,
    reason,
    game_key,
    session_id,
    reference_type,
    reference_id,
    metadata,
    created_at
  )
  values (
    v_user_id,
    'add',
    v_plays,
    v_before,
    v_after,
    format(
      'Tiêu dùng %sđ — đơn %s',
      v_amount,
      v_order.order_code
    ),
    null,
    null,
    'order_spending',
    v_reference_id,
    jsonb_build_object(
      'source',
        'order_spending',
      'order_id',
        v_order.id,
      'order_code',
        v_order.order_code,
      'order_amount',
        v_amount,
      'spend_per_play',
        v_spend_per_play,
      'plays_from_spend_after',
        v_from_spend_after
    ),
    v_now
  );


  /*
   * Backward-compatible profile history projection.
   *
   * This is committed in the same transaction as authoritative
   * ledger + balance mutation.
   */
  insert into
  public.analytics_events (
    user_id,
    event_name,
    event_data,
    metadata,
    created_at
  )
  values (
    v_user_id,
    'plays_added',
    jsonb_build_object(
      'amount',
        v_plays,
      'reason',
        format(
          'Tiêu dùng %sđ — đơn %s',
          v_amount,
          v_order.order_code
        ),
      'source',
        'order_spending',
      'new_total',
        v_after,
      'order_code',
        v_order.order_code,
      'order_amount',
        v_amount,
      'spend_per_play',
        v_spend_per_play
    ),
    jsonb_build_object(
      'order_id',
        v_order.id,
      'reference_type',
        'order_spending',
      'reference_id',
        v_reference_id
    ),
    v_now
  );


  return query
  select
    v_order.id,
    v_user_id,
    v_order.order_code,
    v_amount,
    v_spend_per_play,
    v_plays,
    v_before,
    v_after,
    v_from_spend_after,
    false;
end;
$$;


/*
 * Backend-only bounded authority.
 */
revoke all
on function
public.cing_commerce_award_order_spend_plays_v1(
  bigint
)
from public, anon, authenticated;

grant execute
on function
public.cing_commerce_award_order_spend_plays_v1(
  bigint
)
to service_role;

/*
 * ==========================================================
 * ORDER-SPEND GAME PLAY HISTORICAL BACKFILL V1
 * ==========================================================
 *
 * Production forensic audit identified exactly four canonical
 * commerce orders that were already awarded plays by the
 * legacy Node path before game_play_transactions became the
 * durable order-spending authority:
 *
 *   order 377 -> analytics 2225 -> +1
 *   order 379 -> analytics 2314 -> +1
 *   order 382 -> analytics 3180 -> +1
 *   order 387 -> analytics 3717 -> +22
 *
 * This section reconstructs authoritative ledger history only.
 *
 * CRITICAL:
 * - players.game_plays MUST NOT be changed.
 * - players.plays_from_spend MUST NOT be changed.
 * - analytics_events MUST NOT be duplicated.
 *
 * The existing legacy award already changed the balance.
 */


/*
 * Fail closed if a partial historical dataset is present.
 *
 * Fresh/staging environments with none of these production
 * records may apply the migration without backfill.
 */
do $historical_shape$
declare
  v_target_order_count integer;
  v_target_event_count integer;
  v_existing_ledger_count integer;
begin
  select count(*)
  into v_target_order_count
  from public.orders
  where id in (
    377,
    379,
    382,
    387
  );

  select count(*)
  into v_target_event_count
  from public.analytics_events
  where id in (
    2225,
    2314,
    3180,
    3717
  );

  if
    v_target_order_count > 0
    or v_target_event_count > 0
  then
    if v_target_order_count <> 4 then
      raise exception
        'COMMERCE_ORDER_SPEND_PLAY_BACKFILL_ORDER_SET_CHANGED'
        using errcode = '55000';
    end if;

    if v_target_event_count <> 4 then
      raise exception
        'COMMERCE_ORDER_SPEND_PLAY_BACKFILL_EVENT_SET_CHANGED'
        using errcode = '55000';
    end if;


    /*
     * Canonical payment/order authority must remain intact.
     */
    if (
      select count(*)
      from public.orders o
      join public.payment_transactions p
        on p.id =
          o.payment_transaction_id
      where o.id in (
        377,
        379,
        382,
        387
      )
        and o.payment_status = 'paid'
        and p.payment_status = 'paid'
        and p.payment_purpose = 'order'
        and p.order_created is true
        and p.order_id = o.id
    ) <> 4 then
      raise exception
        'COMMERCE_ORDER_SPEND_PLAY_BACKFILL_PAYMENT_AUTHORITY_CHANGED'
        using errcode = '55000';
    end if;


    /*
     * Exact audited event/order pairing must remain unchanged.
     */
    if (
      select count(*)
      from public.analytics_events ae
      join public.orders o
        on o.order_code =
          ae.event_data ->> 'order_code'
      where
        (
          ae.id = 2225
          and o.id = 377
          and ae.user_id = '0984966336'
          and (ae.event_data ->> 'amount')::integer = 1
          and (ae.event_data ->> 'new_total')::integer = 885
          and (ae.event_data ->> 'order_amount')::bigint = 20100
          and (ae.event_data ->> 'spend_per_play')::bigint = 20000
        )
        or
        (
          ae.id = 2314
          and o.id = 379
          and ae.user_id = '0984966336'
          and (ae.event_data ->> 'amount')::integer = 1
          and (ae.event_data ->> 'new_total')::integer = 889
          and (ae.event_data ->> 'order_amount')::bigint = 20250
          and (ae.event_data ->> 'spend_per_play')::bigint = 20000
        )
        or
        (
          ae.id = 3180
          and o.id = 382
          and ae.user_id = '0984966336'
          and (ae.event_data ->> 'amount')::integer = 1
          and (ae.event_data ->> 'new_total')::integer = 837
          and (ae.event_data ->> 'order_amount')::bigint = 20100
          and (ae.event_data ->> 'spend_per_play')::bigint = 20000
        )
        or
        (
          ae.id = 3717
          and o.id = 387
          and ae.user_id = '0983651389'
          and (ae.event_data ->> 'amount')::integer = 22
          and (ae.event_data ->> 'new_total')::integer = 22
          and (ae.event_data ->> 'order_amount')::bigint = 443000
          and (ae.event_data ->> 'spend_per_play')::bigint = 20000
        )
    ) <> 4 then
      raise exception
        'COMMERCE_ORDER_SPEND_PLAY_BACKFILL_EVENT_SHAPE_CHANGED'
        using errcode = '55000';
    end if;


    /*
     * Identity must still agree with canonical commerce order.
     */
    if exists (
      select 1
      from public.analytics_events ae
      join public.orders o
        on o.order_code =
          ae.event_data ->> 'order_code'
      where ae.id in (
        2225,
        2314,
        3180,
        3717
      )
        and ae.user_id <>
          coalesce(
            nullif(o.user_id, ''),
            nullif(o.customer_phone, ''),
            ''
          )
    ) then
      raise exception
        'COMMERCE_ORDER_SPEND_PLAY_BACKFILL_IDENTITY_CHANGED'
        using errcode = '55000';
    end if;


    select count(*)
    into v_existing_ledger_count
    from public.game_play_transactions
    where reference_type =
        'order_spending'
      and reference_id in (
        '377',
        '379',
        '382',
        '387'
      );

    if v_existing_ledger_count <> 0 then
      raise exception
        'COMMERCE_ORDER_SPEND_PLAY_BACKFILL_ALREADY_PRESENT'
        using errcode = '55000';
    end if;
  end if;
end;
$historical_shape$;


/*
 * Reconstruct the four durable ledger rows from immutable
 * compatibility history.
 *
 * balance_before is derived from:
 *
 *   balance_after - awarded amount
 */
insert into
public.game_play_transactions (
  user_id,
  transaction_type,
  amount,
  balance_before,
  balance_after,
  reason,
  game_key,
  session_id,
  reference_type,
  reference_id,
  metadata,
  created_at
)
select
  ae.user_id,

  'add',

  (ae.event_data ->> 'amount')::integer,

  (
    (ae.event_data ->> 'new_total')::integer
    -
    (ae.event_data ->> 'amount')::integer
  ),

  (ae.event_data ->> 'new_total')::integer,

  coalesce(
    nullif(
      ae.event_data ->> 'reason',
      ''
    ),
    format(
      'Tiêu dùng %sđ — đơn %s',
      ae.event_data ->> 'order_amount',
      o.order_code
    )
  ),

  null,

  null,

  'order_spending',

  o.id::text,

  jsonb_build_object(
    'source',
      'order_spending',

    'historical_backfill',
      true,

    'historical_analytics_event_id',
      ae.id,

    'order_id',
      o.id,

    'order_code',
      o.order_code,

    'order_amount',
      (ae.event_data ->> 'order_amount')::bigint,

    'spend_per_play',
      (ae.event_data ->> 'spend_per_play')::bigint
  ),

  ae.created_at

from public.analytics_events ae

join public.orders o
  on o.order_code =
    ae.event_data ->> 'order_code'

where (
  (
    ae.id = 2225
    and o.id = 377
  )
  or
  (
    ae.id = 2314
    and o.id = 379
  )
  or
  (
    ae.id = 3180
    and o.id = 382
  )
  or
  (
    ae.id = 3717
    and o.id = 387
  )
)

on conflict (
  reference_type,
  reference_id
)
where
  reference_type =
    'order_spending'
  and reference_id is not null

do nothing;


/*
 * Post-backfill assertion runs only when production historical
 * records exist.
 */
do $historical_post$
begin
  if exists (
    select 1
    from public.orders
    where id in (
      377,
      379,
      382,
      387
    )
  ) then
    if (
      select count(*)
      from public.game_play_transactions
      where reference_type =
          'order_spending'
        and reference_id in (
          '377',
          '379',
          '382',
          '387'
        )
    ) <> 4 then
      raise exception
        'COMMERCE_ORDER_SPEND_PLAY_BACKFILL_INCOMPLETE'
        using errcode = '55000';
    end if;


    if exists (
      select 1
      from public.game_play_transactions
      where reference_type =
          'order_spending'
        and reference_id in (
          '377',
          '379',
          '382',
          '387'
        )
        and (
          transaction_type <> 'add'
          or amount <= 0
          or balance_after <>
            balance_before + amount
        )
    ) then
      raise exception
        'COMMERCE_ORDER_SPEND_PLAY_BACKFILL_BALANCE_INVALID'
        using errcode = '55000';
    end if;
  end if;
end;
$historical_post$;


/*
 * Entire foundation + mutations + historical replay fences
 * remain one PostgreSQL transaction.
 */

/*
 * ==========================================================
 * CING COMMERCE — ORDER LOYALTY POINT EFFECT AUTHORITY V1
 * ==========================================================
 *
 * point_transactions is the durable loyalty ledger.
 * players.total_points is the serialized balance projection.
 *
 * These functions intentionally do NOT call iPOS.
 * External iPOS delivery remains application orchestration.
 *
 * points_deduct:
 * - derives user and points from canonical paid order
 * - serializes on players row
 * - fails closed on insufficient / invalid balance
 * - writes balance + durable ledger atomically
 * - exactly once per order
 *
 * points_earn:
 * - derives user / amount from canonical paid order
 * - accepts tier only as the already-resolved commerce tier
 * - PostgreSQL owns the actual point arithmetic
 * - intended only for the existing after-hours local-award path
 * - exactly once per order
 */


/* ----------------------------------------------------------
 * Dedicated Commerce identity on the shared loyalty ledger.
 *
 * point_transactions.order_id is a pre-existing nullable UUID
 * legacy field. Canonical Commerce orders use bigint identity.
 * The legacy UUID column is intentionally preserved unchanged.
 * ---------------------------------------------------------- */

alter table public.point_transactions
add column if not exists
  commerce_order_id bigint;

do $commerce_point_order_fk$
begin
  if not exists (
    select 1
    from pg_constraint c
    join pg_class r
      on r.oid = c.conrelid
    join pg_namespace n
      on n.oid = r.relnamespace
    where n.nspname = 'public'
      and r.relname = 'point_transactions'
      and c.conname =
        'point_transactions_commerce_order_fk'
  ) then
    alter table public.point_transactions
    add constraint
      point_transactions_commerce_order_fk
    foreign key (commerce_order_id)
    references public.orders(id)
    on delete restrict;
  end if;
end;
$commerce_point_order_fk$;


/* ----------------------------------------------------------
 * HISTORICAL POINT-DEDUCTION CLASSIFICATION V1
 *
 * Production forensic audit proved that orders 139 and 185
 * requested loyalty-point deductions, but the legacy deduction
 * side effect did NOT execute.
 *
 * Root cause:
 * the pre-4297e0e payment path passed payment.user_id (UUID)
 * into deductPoints() as the players.user_id lookup identity.
 * The lookup therefore resolved no loyalty player, interpreted
 * the balance as zero, and threw before UPDATE.
 *
 * These are NOT historical deductions and MUST NOT be
 * reconstructed in point_transactions.
 *
 * They are durable known legacy non-executed effects:
 *
 *   139 -> points_used  5 -> NOT_EXECUTED
 *   185 -> points_used 30 -> NOT_EXECUTED
 *
 * IMPORTANT:
 * this classification is intentionally exact-order only.
 * Commit time 4297e0e is not used as a production deployment
 * cutoff because source commit time does not prove deployment
 * time.
 *
 * Fresh/staging environments containing neither production
 * order may apply this migration. A partial or changed forensic
 * dataset fails closed.
 * ---------------------------------------------------------- */

do $legacy_point_deduct_shape$
declare
  v_target_count integer;
begin
  select count(*)
  into v_target_count
  from public.orders
  where id in (
    139,
    185
  );

  if v_target_count > 0 then
    if v_target_count <> 2 then
      raise exception
        'COMMERCE_LEGACY_POINT_DEDUCT_ORDER_SET_CHANGED'
        using errcode = '55000';
    end if;

    /*
     * Exact forensic order shape. Do not generalize this into
     * a timestamp cutoff.
     */
    if (
      select count(*)
      from public.orders o
      where
        (
          o.id = 139
          and o.points_used = 5
          and o.payment_status = 'paid'
        )
        or
        (
          o.id = 185
          and o.points_used = 30
          and o.payment_status = 'paid'
        )
    ) <> 2 then
      raise exception
        'COMMERCE_LEGACY_POINT_DEDUCT_ORDER_SHAPE_CHANGED'
        using errcode = '55000';
    end if;

    /*
     * A reconstructed deduction would falsify history.
     */
    if exists (
      select 1
      from public.point_transactions pt
      where pt.commerce_order_id in (
        139,
        185
      )
        and pt.transaction_type = 'deduct'
    ) then
      raise exception
        'COMMERCE_LEGACY_POINT_DEDUCT_UNEXPECTED_LEDGER'
        using errcode = '55000';
    end if;
  end if;
end;
$legacy_point_deduct_shape$;


/* ----------------------------------------------------------
 * Durable per-order Commerce point-effect uniqueness.
 *
 * Historical production profile contains no canonical Commerce
 * identity rows in point_transactions before this migration.
 * The legacy UUID order_id contract remains untouched.
 * ---------------------------------------------------------- */

create unique index if not exists
  point_transactions_commerce_order_effect_uidx
on public.point_transactions (
  commerce_order_id,
  transaction_type
)
where
  commerce_order_id is not null
  and transaction_type in (
    'deduct',
    'add'
  );


/* ----------------------------------------------------------
 * ORDER POINT DEDUCT
 * ---------------------------------------------------------- */

create or replace function
public.cing_commerce_apply_order_points_deduct_v1(
  p_order_id bigint
)
returns table (
  order_id bigint,
  user_id text,
  points_deducted integer,
  balance_before integer,
  balance_after integer,
  applied boolean
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.orders%rowtype;
  v_player public.players%rowtype;

  v_user_id text;
  v_points integer;

  v_balance_numeric numeric;
  v_before integer;
  v_after integer;

  v_existing public.point_transactions%rowtype;
begin
  if p_order_id is null then
    raise exception
      'COMMERCE_POINT_DEDUCT_ORDER_REQUIRED'
      using errcode = '22023';
  end if;

  select o.*
  into v_order
  from public.orders o
  where o.id = p_order_id;

  if not found then
    raise exception
      'COMMERCE_POINT_DEDUCT_ORDER_NOT_FOUND'
      using errcode = 'P0002';
  end if;

  if v_order.payment_status is distinct from 'paid' then
    raise exception
      'COMMERCE_POINT_DEDUCT_ORDER_NOT_PAID'
      using errcode = '55000';
  end if;

  v_user_id :=
    nullif(
      btrim(
        coalesce(
          v_order.customer_phone,
          v_order.user_id,
          ''
        )
      ),
      ''
    );

  if v_user_id is null then
    raise exception
      'COMMERCE_POINT_DEDUCT_USER_MISSING'
      using errcode = '55000';
  end if;

  begin
    if v_order.points_used is null then
      v_points := 0;
    elsif v_order.points_used <> trunc(v_order.points_used)
       or v_order.points_used < 0
       or v_order.points_used > 2147483647 then
      raise exception
        'COMMERCE_POINT_DEDUCT_AMOUNT_INVALID'
        using errcode = '55000';
    else
      v_points :=
        v_order.points_used::integer;
    end if;
  exception
    when numeric_value_out_of_range then
      raise exception
        'COMMERCE_POINT_DEDUCT_AMOUNT_INVALID'
        using errcode = '55000';
  end;

  if v_points = 0 then
    return query
    select
      v_order.id,
      v_user_id,
      0,
      null::integer,
      null::integer,
      false;

    return;
  end if;

  /*
   * Exact forensic legacy fence.
   *
   * Orders 139 and 185 requested a deduction under the old
   * payment path, but that side effect provably never executed.
   * Replaying either order through the new authority must
   * preserve that historical fact: no balance mutation and no
   * fabricated point_transactions row.
   *
   * Do not replace this with a date/time cutoff.
   */
  if
    (
      v_order.id = 139
      and v_points = 5
    )
    or
    (
      v_order.id = 185
      and v_points = 30
    )
  then
    return query
    select
      v_order.id,
      v_user_id,
      v_points,
      null::integer,
      null::integer,
      false;

    return;
  end if;

  /*
   * Player row is the loyalty-balance serialization boundary.
   */
  select p.*
  into v_player
  from public.players p
  where p.user_id = v_user_id
  for update;

  if not found then
    raise exception
      'COMMERCE_POINT_DEDUCT_PLAYER_NOT_FOUND'
      using errcode = 'P0002';
  end if;

  /*
   * Recheck idempotency AFTER the serialization lock.
   */
  select pt.*
  into v_existing
  from public.point_transactions pt
  where pt.commerce_order_id = v_order.id
    and pt.transaction_type = 'deduct'
  limit 1;

  if found then
    return query
    select
      v_order.id,
      v_user_id,
      abs(v_existing.points)::integer,
      v_existing.balance_before::integer,
      v_existing.balance_after::integer,
      false;

    return;
  end if;

  v_balance_numeric :=
    coalesce(
      v_player.total_points,
      0
    );

  if v_balance_numeric <> trunc(v_balance_numeric)
     or v_balance_numeric < 0
     or v_balance_numeric > 2147483647 then
    raise exception
      'COMMERCE_POINT_BALANCE_DOMAIN_INVALID'
      using errcode = '55000';
  end if;

  v_before :=
    v_balance_numeric::integer;

  if v_before < v_points then
    raise exception
      'COMMERCE_POINT_DEDUCT_INSUFFICIENT_POINTS'
      using errcode = 'P0001';
  end if;

  v_after :=
    v_before - v_points;

  update public.players p
  set total_points = v_after
  where p.user_id = v_user_id;

  insert into public.point_transactions (
    user_id,
    commerce_order_id,
    transaction_type,
    points,
    balance_before,
    balance_after,
    reason,
    metadata
  )
  values (
    v_user_id,
    v_order.id,
    'deduct',
    -v_points,
    v_before,
    v_after,
    'Thanh toán đơn hàng ' || v_order.order_code,
    jsonb_build_object(
      'source',
      'commerce_order',
      'effect_key',
      'points_deduct',
      'order_code',
      v_order.order_code
    )
  );

  return query
  select
    v_order.id,
    v_user_id,
    v_points,
    v_before,
    v_after,
    true;
end;
$$;


/* ----------------------------------------------------------
 * ORDER AFTER-HOURS POINT EARN
 *
 * Existing production contract:
 *
 * member / loyal / silver / gold / diamond / partner = 10%
 * loyal_partner                                      = 15%
 *
 * points =
 * floor(total_amount * point_rate / 1000)
 *
 * PostgreSQL derives amount from canonical paid order.
 * ---------------------------------------------------------- */

create or replace function
public.cing_commerce_apply_order_points_earn_v1(
  p_order_id bigint,
  p_tier_key text
)
returns table (
  order_id bigint,
  user_id text,
  tier_key text,
  points_added integer,
  balance_before integer,
  balance_after integer,
  applied boolean
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.orders%rowtype;
  v_player public.players%rowtype;

  v_user_id text;
  v_tier text;

  v_rate numeric;
  v_amount numeric;
  v_points_numeric numeric;
  v_points integer;

  v_balance_numeric numeric;
  v_before integer;
  v_after integer;

  v_existing public.point_transactions%rowtype;
begin
  if p_order_id is null then
    raise exception
      'COMMERCE_POINT_EARN_ORDER_REQUIRED'
      using errcode = '22023';
  end if;

  select o.*
  into v_order
  from public.orders o
  where o.id = p_order_id;

  if not found then
    raise exception
      'COMMERCE_POINT_EARN_ORDER_NOT_FOUND'
      using errcode = 'P0002';
  end if;

  if v_order.payment_status is distinct from 'paid' then
    raise exception
      'COMMERCE_POINT_EARN_ORDER_NOT_PAID'
      using errcode = '55000';
  end if;

  v_user_id :=
    nullif(
      btrim(
        coalesce(
          v_order.customer_phone,
          v_order.user_id,
          ''
        )
      ),
      ''
    );

  if v_user_id is null then
    raise exception
      'COMMERCE_POINT_EARN_USER_MISSING'
      using errcode = '55000';
  end if;

  v_tier :=
    lower(
      btrim(
        coalesce(
          nullif(p_tier_key, ''),
          'member'
        )
      )
    );

  v_rate :=
    case v_tier
      when 'member' then 0.10
      when 'loyal' then 0.10
      when 'silver' then 0.10
      when 'gold' then 0.10
      when 'diamond' then 0.10
      when 'partner' then 0.10
      when 'loyal_partner' then 0.15
      else null
    end;

  if v_rate is null then
    raise exception
      'COMMERCE_POINT_EARN_TIER_INVALID'
      using errcode = '22023';
  end if;

  v_amount :=
    coalesce(
      v_order.total_amount,
      0
    );

  if v_amount <> trunc(v_amount)
     or v_amount < 0 then
    raise exception
      'COMMERCE_POINT_EARN_ORDER_AMOUNT_INVALID'
      using errcode = '55000';
  end if;

  v_points_numeric :=
    floor(
      (v_amount * v_rate) /
      1000
    );

  if v_points_numeric < 0
     or v_points_numeric > 2147483647 then
    raise exception
      'COMMERCE_POINT_EARN_AMOUNT_OUT_OF_RANGE'
      using errcode = '22003';
  end if;

  v_points :=
    v_points_numeric::integer;

  if v_points = 0 then
    return query
    select
      v_order.id,
      v_user_id,
      v_tier,
      0,
      null::integer,
      null::integer,
      false;

    return;
  end if;

  select p.*
  into v_player
  from public.players p
  where p.user_id = v_user_id
  for update;

  if not found then
    raise exception
      'COMMERCE_POINT_EARN_PLAYER_NOT_FOUND'
      using errcode = 'P0002';
  end if;

  /*
   * Recheck durable award AFTER player serialization.
   */
  select pt.*
  into v_existing
  from public.point_transactions pt
  where pt.commerce_order_id = v_order.id
    and pt.transaction_type = 'add'
  limit 1;

  if found then
    return query
    select
      v_order.id,
      v_user_id,
      v_tier,
      abs(v_existing.points)::integer,
      v_existing.balance_before::integer,
      v_existing.balance_after::integer,
      false;

    return;
  end if;

  v_balance_numeric :=
    coalesce(
      v_player.total_points,
      0
    );

  if v_balance_numeric <> trunc(v_balance_numeric)
     or v_balance_numeric < 0
     or v_balance_numeric > 2147483647 then
    raise exception
      'COMMERCE_POINT_BALANCE_DOMAIN_INVALID'
      using errcode = '55000';
  end if;

  v_before :=
    v_balance_numeric::integer;

  if
    v_before >
      2147483647 - v_points
  then
    raise exception
      'COMMERCE_POINT_EARN_BALANCE_OVERFLOW'
      using errcode = '22003';
  end if;

  v_after :=
    v_before + v_points;

  update public.players p
  set total_points = v_after
  where p.user_id = v_user_id;

  insert into public.point_transactions (
    user_id,
    commerce_order_id,
    transaction_type,
    points,
    balance_before,
    balance_after,
    reason,
    metadata
  )
  values (
    v_user_id,
    v_order.id,
    'add',
    v_points,
    v_before,
    v_after,
    'Tích điểm đơn hàng '
      || v_order.order_code
      || ' ('
      || v_tier
      || ')',
    jsonb_build_object(
      'source',
      'after_hours_app_order',
      'effect_key',
      'points_earn',
      'order_code',
      v_order.order_code,
      'tier',
      v_tier,
      'point_rate',
      v_rate
    )
  );

  return query
  select
    v_order.id,
    v_user_id,
    v_tier,
    v_points,
    v_before,
    v_after,
    true;
end;
$$;


/* ----------------------------------------------------------
 * Backend-only authority.
 * ---------------------------------------------------------- */

revoke all on function
  public.cing_commerce_apply_order_points_deduct_v1(bigint)
from public;

revoke all on function
  public.cing_commerce_apply_order_points_deduct_v1(bigint)
from anon;

revoke all on function
  public.cing_commerce_apply_order_points_deduct_v1(bigint)
from authenticated;

grant execute on function
  public.cing_commerce_apply_order_points_deduct_v1(bigint)
to service_role;


revoke all on function
  public.cing_commerce_apply_order_points_earn_v1(bigint, text)
from public;

revoke all on function
  public.cing_commerce_apply_order_points_earn_v1(bigint, text)
from anon;

revoke all on function
  public.cing_commerce_apply_order_points_earn_v1(bigint, text)
from authenticated;

grant execute on function
  public.cing_commerce_apply_order_points_earn_v1(bigint, text)
to service_role;

commit;
