begin;

/*
 * CING OFFLINE REVIVAL
 * DAILY REWARD NOTIFICATION IDEMPOTENCY
 *
 * Preserve the existing notifications table
 * and all unrelated notification types.
 *
 * A canonical daily challenge can create
 * at most one Revival winner notification.
 */

create unique index
  cing_revive_daily_reward_notification_uk

on public.notifications (
  (metadata ->> 'daily_challenge_id')
)

where source_event =
    'cing_offline_revive_daily_reward'
  and metadata ? 'daily_challenge_id';

/*
 * Link the committed reward to the stable
 * notification ID generated by PostgreSQL.
 */

alter table
  public.cing_offline_revive_score_outbox

add column reward_notification_id bigint
  references public.notifications(id)
  on delete restrict;

alter table public.cing_offline_revive_score_outbox
  add column reward_notification_attempt_count integer not null default 0,
  add column reward_notification_next_attempt_at timestamptz not null default now(),
  add column reward_notification_worker_token uuid,
  add column reward_notification_locked_until timestamptz,
  add column reward_notification_last_error text;

alter table public.cing_offline_revive_score_outbox
  add constraint cing_revive_notification_lease_ck
  check (
    (
      reward_notification_status = 'processing'
      and reward_notification_worker_token is not null
      and reward_notification_locked_until is not null
    )
    or
    (
      reward_notification_status is distinct from 'processing'
      and reward_notification_worker_token is null
      and reward_notification_locked_until is null
    )
  );

create function
public.cing_offline_revive_reward_notification_create_v1(
  p_score_id bigint,
  p_worker_token uuid
)
returns table (
  notification_id bigint,
  created boolean
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_outbox public.cing_offline_revive_score_outbox%rowtype;
  v_points integer;
  v_id bigint;
  v_created boolean := false;
begin
  if p_score_id is null
    or p_score_id <= 0
    or p_worker_token is null
  then
    raise exception 'REVIVAL_NOTIFICATION_ARGUMENT_INVALID';
  end if;

  select o.* into v_outbox
  from public.cing_offline_revive_score_outbox o
  where o.score_id = p_score_id
  for update;

  if not found
    or v_outbox.reward_status is distinct from 'completed'
    or v_outbox.reward_applied is distinct from true
    or v_outbox.reward_challenge_id is null
    or v_outbox.reward_snapshot_id is null
    or v_outbox.reward_notification_status is distinct from 'processing'
    or v_outbox.reward_notification_worker_token is distinct from p_worker_token
    or v_outbox.reward_notification_locked_until <= clock_timestamp()
  then
    raise exception 'REVIVAL_NOTIFICATION_REWARD_NOT_READY';
  end if;

  select t.points::integer into v_points
  from public.point_transactions t
  where t.daily_challenge_id = v_outbox.reward_challenge_id
    and t.transaction_type = 'add'
    and t.user_id = v_outbox.user_id
    and t.metadata ->> 'revival_session_id' = v_outbox.session_id::text
    and t.metadata ->> 'revival_score_id' = v_outbox.score_id::text
    and t.metadata ->> 'challenge_snapshot_id' = v_outbox.reward_snapshot_id::text;

  if not found or v_points is null or v_points <= 0 then
    raise exception 'REVIVAL_NOTIFICATION_LEDGER_MISMATCH';
  end if;


  insert into public.notifications (
    user_id, title, message, type,
    notification_type, source_event,
    metadata, data, is_read
  )
  values (
    v_outbox.user_id,
    '🏆 Nhận thưởng thử thách ngày!',
    format('Chúc mừng! Bạn nhận được +%s điểm tích lũy.', v_points),
    'daily_challenge_reward',
    'daily_challenge_reward',
    'cing_offline_revive_daily_reward',
    jsonb_build_object(
      'daily_challenge_id', v_outbox.reward_challenge_id,
      'revival_session_id', v_outbox.session_id,
      'revival_score_id', v_outbox.score_id,
      'challenge_snapshot_id', v_outbox.reward_snapshot_id
    ),
    jsonb_build_object(
      'reward_points', v_points,
      'game_key', v_outbox.game_key,
      'session_id', v_outbox.session_id,
      'delay_if_in_game', true
    ),
    false
  )
  on conflict do nothing
  returning id into v_id;

  v_created := v_id is not null;

  if v_id is null then
    select n.id into v_id
    from public.notifications n
    where n.source_event = 'cing_offline_revive_daily_reward'
      and n.metadata ->> 'daily_challenge_id'
        = v_outbox.reward_challenge_id::text
      and n.user_id = v_outbox.user_id
      and n.metadata ->> 'revival_session_id'
        = v_outbox.session_id::text
      and n.metadata ->> 'revival_score_id'
        = v_outbox.score_id::text
      and n.metadata ->> 'challenge_snapshot_id'
        = v_outbox.reward_snapshot_id::text
      and n.data ->> 'reward_points' = v_points::text;
    if not found then
      raise exception 'REVIVAL_NOTIFICATION_IDENTITY_CONFLICT';
    end if;
  end if;

  if v_outbox.reward_notification_id is not null
    and v_outbox.reward_notification_id <> v_id then
    raise exception 'REVIVAL_NOTIFICATION_OUTBOX_ID_CONFLICT';
  end if;

  update public.cing_offline_revive_score_outbox o
  set reward_notification_id = v_id
  where o.score_id = v_outbox.score_id;

  return query select v_id, v_created;
end;
$$;

revoke all on function
public.cing_offline_revive_reward_notification_create_v1(bigint, uuid)
from public, anon, authenticated, service_role;

grant execute on function
public.cing_offline_revive_reward_notification_create_v1(bigint, uuid)
to service_role;


/* Independent notification claim; no financial mutation. */
create function
public.cing_offline_revive_reward_notification_claim_v1(
  p_lease_seconds integer default 300
)
returns setof public.cing_offline_revive_score_outbox
language plpgsql
security definer
set search_path = public
as $$
declare
  v_score_id bigint;
  v_row public.cing_offline_revive_score_outbox%rowtype;
  v_now timestamptz := clock_timestamp();
begin
  if p_lease_seconds is null
    or p_lease_seconds < 30
    or p_lease_seconds > 900 then
    raise exception 'REVIVAL_NOTIFICATION_LEASE_ARGUMENT_INVALID'
      using errcode = '22023';
  end if;

  select o.score_id into v_score_id
  from public.cing_offline_revive_score_outbox o
  where o.reward_status = 'completed'
    and o.reward_applied is true
    and (
      (
        o.reward_notification_status = 'pending'
        and o.reward_notification_next_attempt_at <= v_now
      )
      or
      (
        o.reward_notification_status = 'processing'
        and o.reward_notification_locked_until <= v_now
      )
    )
  order by
    o.reward_notification_next_attempt_at,
    o.score_id
  for update skip locked
  limit 1;

  if not found then return; end if;

  update public.cing_offline_revive_score_outbox o
  set reward_notification_status = 'processing',
      reward_notification_attempt_count =
        o.reward_notification_attempt_count + 1,
      reward_notification_worker_token = gen_random_uuid(),
      reward_notification_locked_until =
        clock_timestamp()
        + make_interval(secs => p_lease_seconds),
      reward_notification_last_error = null
  where o.score_id = v_score_id
  returning * into v_row;

  return next v_row;
end;
$$;

revoke all on function
public.cing_offline_revive_reward_notification_claim_v1(integer)
from public, anon, authenticated, service_role;

grant execute on function
public.cing_offline_revive_reward_notification_claim_v1(integer)
to service_role;

create function
public.cing_offline_revive_reward_notification_ack_v1(
  p_score_id bigint,
  p_worker_token uuid,
  p_notification_id bigint
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_score_id is null or p_score_id <= 0
    or p_worker_token is null
    or p_notification_id is null or p_notification_id <= 0
  then
    raise exception 'REVIVAL_NOTIFICATION_ACK_ARGUMENT_INVALID'
      using errcode = '22023';
  end if;

  update public.cing_offline_revive_score_outbox o
  set reward_notification_status = 'delivered',
      reward_notification_sent_at = clock_timestamp(),
      reward_notification_worker_token = null,
      reward_notification_locked_until = null,
      reward_notification_last_error = null
  where o.score_id = p_score_id
    and o.reward_status = 'completed'
    and o.reward_applied is true
    and o.reward_notification_id = p_notification_id
    and o.reward_notification_status = 'processing'
    and o.reward_notification_worker_token = p_worker_token
    and o.reward_notification_locked_until > clock_timestamp()
    and exists (
      select 1 from public.notifications n
      where n.id = p_notification_id
        and n.user_id = o.user_id
        and n.source_event = 'cing_offline_revive_daily_reward'
        and n.metadata ->> 'daily_challenge_id'
          = o.reward_challenge_id::text
        and n.metadata ->> 'revival_session_id'
          = o.session_id::text
    );

  return found;
end;
$$;

revoke all on function
public.cing_offline_revive_reward_notification_ack_v1(bigint, uuid, bigint)
from public, anon, authenticated, service_role;

grant execute on function
public.cing_offline_revive_reward_notification_ack_v1(bigint, uuid, bigint)
to service_role;

/*
 * Notification failure changes notification state only.
 * A persisted notification ID is never discarded.
 */
create function
public.cing_offline_revive_reward_notification_fail_v1(
  p_score_id bigint,
  p_worker_token uuid,
  p_error text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_score_id is null
    or p_score_id <= 0
    or p_worker_token is null
    or nullif(btrim(coalesce(p_error, '')), '') is null
  then
    raise exception 'REVIVAL_NOTIFICATION_FAIL_ARGUMENT_INVALID'
      using errcode = '22023';
  end if;

  update public.cing_offline_revive_score_outbox o
  set
    reward_notification_status = case
      when o.reward_notification_id is not null
        then 'pending'
      when o.reward_notification_attempt_count >= 6
        then 'failed'
      else 'pending'
    end,
    reward_notification_next_attempt_at =
      clock_timestamp() + make_interval(
        secs => case
          when o.reward_notification_attempt_count <= 1 then 10
          when o.reward_notification_attempt_count = 2 then 30
          when o.reward_notification_attempt_count = 3 then 120
          when o.reward_notification_attempt_count = 4 then 600
          else 1800
        end
      ),
    reward_notification_worker_token = null,
    reward_notification_locked_until = null,
    reward_notification_last_error = left(btrim(p_error), 1000)
  where o.score_id = p_score_id
    and o.reward_status = 'completed'
    and o.reward_applied is true
    and o.reward_notification_status = 'processing'
    and o.reward_notification_worker_token = p_worker_token
    and o.reward_notification_locked_until > clock_timestamp();

  return found;
end;
$$;

revoke all on function
public.cing_offline_revive_reward_notification_fail_v1(
  bigint, uuid, text
)
from public, anon, authenticated, service_role;

grant execute on function
public.cing_offline_revive_reward_notification_fail_v1(
  bigint, uuid, text
)
to service_role;

commit;
