begin;

/*
 * CING GAME CENTER V2
 * REVIVE CREDIT FOUNDATION V1
 *
 * ADDITIVE SCHEMA ONLY.
 *
 * This migration intentionally does NOT:
 * - alter players.game_plays
 * - convert legacy balances
 * - debit Cing Wallet
 * - mutate loyalty points
 * - change Block Puzzle sessions
 * - activate revival purchases
 *
 * Balance mutations will be owned by subsequent
 * PostgreSQL authority functions.
 */

create table public.cing_revive_credit_balances (

  user_id text primary key,

  balance integer
    not null
    default 0,

  created_at timestamptz
    not null
    default now(),

  updated_at timestamptz
    not null
    default now(),

  constraint cing_revive_credit_balances_user_ck
    check (btrim(user_id) <> ''),

  constraint cing_revive_credit_balances_nonnegative_ck
    check (balance >= 0)

);


/*
 * Durable history of revival balance mutations.
 *
 * One row represents one completed resource mutation.
 * The ledger never represents Wallet money or
 * iPOS loyalty points.
 */

create table public.cing_revive_credit_transactions (

  id bigint
    generated by default as identity
    primary key,

  user_id text
    not null,

  transaction_type text
    not null,

  amount integer
    not null,

  balance_before integer
    not null,

  balance_after integer
    not null,

  reason text
    not null,

  game_key text,

  session_id uuid,

  reference_type text
    not null,

  reference_id text
    not null,

  metadata jsonb
    not null
    default '{}'::jsonb,

  created_at timestamptz
    not null
    default now(),

  constraint cing_revive_credit_tx_user_ck
    check (btrim(user_id) <> ''),

  constraint cing_revive_credit_tx_type_ck
    check (
      transaction_type in (
        'add',
        'deduct',
        'adjust'
      )
    ),

  constraint cing_revive_credit_tx_amount_ck
    check (amount <> 0),

  constraint cing_revive_credit_tx_direction_ck
    check (
      (
        transaction_type = 'add'
        and amount > 0
      )
      or
      (
        transaction_type = 'deduct'
        and amount < 0
      )
      or
      (
        transaction_type = 'adjust'
        and amount <> 0
      )
    ),

  constraint cing_revive_credit_tx_before_ck
    check (balance_before >= 0),

  constraint cing_revive_credit_tx_after_ck
    check (balance_after >= 0),

  constraint cing_revive_credit_tx_math_ck
    check (
      balance_after =
        balance_before + amount
    ),

  constraint cing_revive_credit_tx_reason_ck
    check (btrim(reason) <> ''),

  constraint cing_revive_credit_tx_game_ck
    check (
      game_key is null
      or btrim(game_key) <> ''
    ),

  constraint cing_revive_credit_tx_reference_type_ck
    check (btrim(reference_type) <> ''),

  constraint cing_revive_credit_tx_reference_id_ck
    check (btrim(reference_id) <> ''),

  constraint cing_revive_credit_tx_metadata_ck
    check (
      jsonb_typeof(metadata) = 'object'
    )

);


/*
 * One mutation per canonical user + business reference.
 *
 * Reference IDs must be created and validated
 * by the corresponding backend/SQL authority.
 */

create unique index
  cing_revive_credit_tx_reference_uq

on public.cing_revive_credit_transactions (

  user_id,
  reference_type,
  reference_id

);


/*
 * Customer history / Admin audit access.
 */

create index
  cing_revive_credit_tx_user_created_idx

on public.cing_revive_credit_transactions (

  user_id,
  created_at desc,
  id desc

);


/*
 * Global chronological audit access.
 */

create index
  cing_revive_credit_tx_created_idx

on public.cing_revive_credit_transactions (

  created_at desc,
  id desc

);


/*
 * Balance and ledger are authority-only.
 *
 * Service role may read.
 * Mutation functions will be introduced separately.
 */

revoke all
on table public.cing_revive_credit_balances
from public, anon, authenticated, service_role;

revoke all
on table public.cing_revive_credit_transactions
from public, anon, authenticated, service_role;

grant select
on table public.cing_revive_credit_balances
to service_role;

grant select
on table public.cing_revive_credit_transactions
to service_role;


/*
 * No player balance update.
 * No backfill.
 * No financial mutation.
 */

commit;
