begin;

/*
 * ==========================================================
 * CING GAME PLAY TRANSACTION LEDGER V1
 * ==========================================================
 *
 * Durable authority for game-play balance mutations.
 *
 * analytics_events remains a compatibility / telemetry
 * projection and is not the authoritative ledger.
 */

create table public.game_play_transactions (
  id bigint
    generated by default as identity
    primary key,

  user_id text
    not null,

  transaction_type text
    not null,

  amount integer
    not null,

  balance_before integer
    not null,

  balance_after integer
    not null,

  reason text
    not null,

  game_key text,

  session_id uuid,

  reference_type text,

  reference_id text,

  metadata jsonb
    not null
    default '{}'::jsonb,

  created_at timestamptz
    not null
    default now(),

  constraint game_play_transactions_type_ck
    check (
      transaction_type in (
        'add',
        'deduct',
        'adjust'
      )
    ),

  constraint game_play_transactions_amount_ck
    check (
      amount <> 0
    ),

  constraint game_play_transactions_direction_ck
    check (
      (
        transaction_type = 'add'
        and amount > 0
      )
      or (
        transaction_type = 'deduct'
        and amount < 0
      )
      or (
        transaction_type = 'adjust'
        and amount <> 0
      )
    ),

  constraint game_play_transactions_balance_before_ck
    check (
      balance_before >= 0
    ),

  constraint game_play_transactions_balance_after_ck
    check (
      balance_after >= 0
    ),

  constraint game_play_transactions_balance_math_ck
    check (
      balance_after =
        balance_before + amount
    ),

  constraint game_play_transactions_reason_ck
    check (
      btrim(reason) <> ''
    ),

  constraint game_play_transactions_game_key_ck
    check (
      game_key is null
      or btrim(game_key) <> ''
    ),

  constraint game_play_transactions_reference_type_ck
    check (
      reference_type is null
      or btrim(reference_type) <> ''
    ),

  constraint game_play_transactions_reference_id_ck
    check (
      reference_id is null
      or btrim(reference_id) <> ''
    )
);


/*
 * One durable play mutation per gameplay session.
 */
create unique index
  game_play_transactions_game_session_uq
on public.game_play_transactions (
  game_key,
  session_id
)
where session_id is not null;


/*
 * Primary history access path.
 */
create index
  game_play_transactions_user_created_idx
on public.game_play_transactions (
  user_id,
  created_at desc
);


/*
 * Ledger is backend-readable but mutations are authority-only.
 *
 * SECURITY DEFINER gameplay RPC owns transactional writes.
 */
revoke all
on table public.game_play_transactions
from public;

revoke all
on table public.game_play_transactions
from anon;

revoke all
on table public.game_play_transactions
from authenticated;

revoke all
on table public.game_play_transactions
from service_role;

grant select
on table public.game_play_transactions
to service_role;


/*
 * Upgrade existing session-start authority so that:
 *
 * player balance mutation
 * + gameplay session
 * + durable ledger
 * + analytics compatibility projection
 *
 * are one PostgreSQL transaction.
 */

create or replace function public.cing_block_puzzle_start_session_atomic(
  p_session_id uuid,
  p_request_id uuid,
  p_user_id text,
  p_seed bigint,
  p_engine_version integer,
  p_rules_version integer,
  p_score_version integer,
  p_replay_version integer,
  p_ttl_seconds integer
)
returns public.cing_block_puzzle_sessions
language plpgsql
security definer
set search_path = public
as $$
declare
  v_existing public.cing_block_puzzle_sessions%rowtype;
  v_player public.players%rowtype;
  v_config jsonb;
  v_game_policy jsonb;
  v_economy_type text;
  v_now timestamptz := clock_timestamp();
  v_session public.cing_block_puzzle_sessions%rowtype;
  v_balance_before integer;
  v_balance_after integer;
begin
  if p_session_id is null then
    raise exception 'BLOCK_PUZZLE_SESSION_ID_REQUIRED'
      using errcode = '22023';
  end if;

  if p_request_id is null then
    raise exception 'BLOCK_PUZZLE_REQUEST_ID_REQUIRED'
      using errcode = '22023';
  end if;

  if p_user_id is null or btrim(p_user_id) = '' then
    raise exception 'BLOCK_PUZZLE_USER_ID_REQUIRED'
      using errcode = '22023';
  end if;

  if p_seed is null or p_seed < 1 or p_seed > 4294967295 then
    raise exception 'BLOCK_PUZZLE_INVALID_SEED'
      using errcode = '22023';
  end if;

  if
    p_engine_version <> 1
    or p_rules_version <> 1
    or p_score_version <> 1
    or p_replay_version <> 1
  then
    raise exception 'BLOCK_PUZZLE_UNSUPPORTED_VERSION'
      using errcode = '22023';
  end if;

  if p_ttl_seconds is null or p_ttl_seconds < 300 or p_ttl_seconds > 86400 then
    raise exception 'BLOCK_PUZZLE_INVALID_TTL'
      using errcode = '22023';
  end if;

  /*
   * Idempotent retry:
   * same authenticated user + same request_id returns
   * the original session and MUST NOT consume another play.
   */
  select *
    into v_existing
  from public.cing_block_puzzle_sessions
  where user_id = p_user_id
    and request_id = p_request_id;

  if found then
    return v_existing;
  end if;

  /*
   * Economy configuration remains DB-driven.
   * No game-specific paid/free decision is trusted from client.
   */
  select game_economy_config
    into v_config
  from public.app_configs
  where id = 1;

  if v_config is null then
    raise exception 'GAME_ECONOMY_CONFIG_UNAVAILABLE'
      using errcode = '55000';
  end if;

  v_game_policy :=
    v_config #> array['games', 'cing-block-puzzle'];

  if v_game_policy is null then
    raise exception 'GAME_POLICY_NOT_CONFIGURED'
      using errcode = '55000';
  end if;

  v_economy_type :=
    btrim(coalesce(v_game_policy ->> 'economy_type', ''));

  if v_economy_type <> 'paid_offline' then
    raise exception 'BLOCK_PUZZLE_REQUIRES_PAID_OFFLINE'
      using errcode = '55000';
  end if;

  /*
   * Row lock serializes concurrent starts for this player.
   */
  select *
    into v_player
  from public.players
  where user_id = p_user_id
  for update;

  if not found then
    raise exception 'PLAYER_NOT_FOUND'
      using errcode = 'P0002';
  end if;

  /*
   * Critical concurrent-idempotency fence.
   *
   * The player row lock serializes session starts for this user.
   * A concurrent retry may have passed the optimistic precheck
   * before waiting on this lock. Re-check after the lock and
   * BEFORE consuming a play.
   */
  select *
    into v_existing
  from public.cing_block_puzzle_sessions
  where user_id = p_user_id
    and request_id = p_request_id;

  if found then
    return v_existing;
  end if;

  if coalesce(v_player.game_plays, 0) < 1 then
    raise exception 'NO_GAME_PLAYS'
      using errcode = 'P0001';
  end if;

  v_balance_before :=
    coalesce(v_player.game_plays, 0);

  update public.players
  set game_plays = game_plays - 1
  where user_id = p_user_id
  returning game_plays
    into v_balance_after;

  if v_balance_after <> v_balance_before - 1 then
    raise exception 'BLOCK_PUZZLE_PLAY_BALANCE_INVARIANT'
      using errcode = '55000';
  end if;

  insert into public.cing_block_puzzle_sessions (
    id,
    request_id,
    user_id,
    game_key,
    seed,
    engine_version,
    rules_version,
    score_version,
    replay_version,
    play_cost,
    status,
    created_at,
    expires_at
  )
  values (
    p_session_id,
    p_request_id,
    p_user_id,
    'cing-block-puzzle',
    p_seed,
    1,
    1,
    1,
    1,
    1,
    'active',
    v_now,
    v_now + make_interval(secs => p_ttl_seconds)
  )
  returning *
    into v_session;

  /*
   * Durable play ledger authority.
   * This write is part of the same PostgreSQL transaction
   * as the balance decrement and gameplay session creation.
   */
  insert into public.game_play_transactions (
    user_id,
    transaction_type,
    amount,
    balance_before,
    balance_after,
    reason,
    game_key,
    session_id,
    reference_type,
    reference_id,
    metadata,
    created_at
  )
  values (
    p_user_id,
    'deduct',
    -1,
    v_balance_before,
    v_balance_after,
    'Chơi Cing Block Puzzle',
    'cing-block-puzzle',
    p_session_id,
    'game_session',
    p_session_id::text,
    jsonb_build_object(
      'request_id',
      p_request_id,
      'engine_version',
      p_engine_version,
      'rules_version',
      p_rules_version,
      'score_version',
      p_score_version,
      'replay_version',
      p_replay_version
    ),
    v_now
  );

  /*
   * Backward-compatible history projection.
   *
   * Existing production profile history reads analytics_events,
   * therefore the compatibility event is committed atomically
   * with the authoritative ledger entry.
   */
  insert into public.analytics_events (
    user_id,
    event_name,
    event_data,
    metadata,
    created_at
  )
  values (
    p_user_id,
    'plays_deducted',
    jsonb_build_object(
      'amount',
      -1,
      'reason',
      'Chơi Cing Block Puzzle',
      'new_total',
      v_balance_after,
      'source',
      'game_session',
      'game_key',
      'cing-block-puzzle',
      'session_id',
      p_session_id
    ),
    jsonb_build_object(
      'session_id',
      p_session_id,
      'request_id',
      p_request_id
    ),
    v_now
  );

  return v_session;
end;
$$;

/*
 * Preserve private backend execution authority explicitly.
 */
revoke all
on function public.cing_block_puzzle_start_session_atomic(
  uuid,
  uuid,
  text,
  bigint,
  integer,
  integer,
  integer,
  integer,
  integer
)
from public;

revoke all
on function public.cing_block_puzzle_start_session_atomic(
  uuid,
  uuid,
  text,
  bigint,
  integer,
  integer,
  integer,
  integer,
  integer
)
from anon;

revoke all
on function public.cing_block_puzzle_start_session_atomic(
  uuid,
  uuid,
  text,
  bigint,
  integer,
  integer,
  integer,
  integer,
  integer
)
from authenticated;

grant execute
on function public.cing_block_puzzle_start_session_atomic(
  uuid,
  uuid,
  text,
  bigint,
  integer,
  integer,
  integer,
  integer,
  integer
)
to service_role;

commit;
