"use strict";const test=require('node:test'),assert=require('node:assert/strict');
const {createPlazaSocialServiceV16,jpegSize}=require('../plazaSocialServiceV16');
const MEMBER='00000000-0000-4000-8000-000000000001',COMMAND='00000000-0000-4000-8000-000000000003';
function setup(options={}){const calls=[];const tables={app_configs:{customer_multiplayer_enabled:true},players:{user_id:'0900000001',is_blocked:false,display_name:'Trusted',crm_tier:'member',custom_badges:[],selected_badge:'member'},cing_plaza_character_profiles_v7:{character:'boy'}};const supabase={from:table=>{const q={select(){return q;},eq(){return q;},maybeSingle:async()=>({data:tables[table]||null}),gt(){return q;},order(){return q;},limit:async()=>({data:[]})};return q;},rpc:async(name,args)=>{calls.push({name,args});return {data:{ok:true}};}};return {calls,service:createPlazaSocialServiceV16({supabase,enabled:()=>true,commerceEnabled:()=>true,...options}),customer:{id:MEMBER,phone:'84900000001',name:'Customer'}};}
test('server takes identity from authenticated customer, never body member/phone/price',async()=>{const s=setup();await s.service.command(s.customer,{operation:'convert',commandId:COMMAND,quantity:10,memberId:'FORGED',price:1,phone:'0900000002'});assert.deepEqual(s.calls[0].args,{p_member_id:MEMBER,p_operation:'convert',p_command_id:COMMAND,p_payload:{quantity:10}});});
test('commerce switch closes conversion before any financial RPC',async()=>{const s=setup({commerceEnabled:()=>false});await assert.rejects(s.service.command(s.customer,{operation:'convert',commandId:COMMAND,quantity:1}),{code:'PLAZA_COMMERCE_UNAVAILABLE'});assert.equal(s.calls.length,0);});
test('fractional, negative and oversized amounts fail before RPC',async()=>{const s=setup();for(const quantity of [1.5,-1,0,1000001,Infinity,'10'])await assert.rejects(s.service.command(s.customer,{operation:'convert',commandId:COMMAND,quantity}),{code:'PLAZA_INVALID_QUANTITY'});assert.equal(s.calls.length,0);});
test('missing authenticated member cannot operate',async()=>{const s=setup();await assert.rejects(s.service.command({phone:'0900000001'},{operation:'convert',commandId:COMMAND,quantity:1}),{code:'PLAZA_UNAUTHORIZED'});assert.equal(s.calls.length,0);});
test('disabled feature never reads DB or calls an authority',async()=>{const s=setup({enabled:()=>false});await assert.rejects(s.service.overview(s.customer),{code:'PLAZA_SOCIAL_UNAVAILABLE'});});
test('avatar validates byte signature, dimensions, file size and JPEG termination',()=>{const valid=Buffer.from([255,216,255,192,0,11,8,0,20,0,30,1,1,17,0,255,217]);assert.deepEqual(jpegSize(valid),{width:30,height:20});for(const bytes of [Buffer.from('<svg/>'),Buffer.alloc(262145),valid.subarray(0,-2)])assert.throws(()=>jpegSize(bytes),{code:'PLAZA_INVALID_AVATAR'});const wide=Buffer.from(valid);wide.writeUInt16BE(600,9);assert.throws(()=>jpegSize(wide),{code:'PLAZA_INVALID_AVATAR'});});
test('only a fully decoded JPEG is uploaded, with metadata removed and an owner-bound key',async()=>{const jpeg=require('jpeg-js');let saved=null;const tables={app_configs:{customer_multiplayer_enabled:true},players:{is_blocked:false},cing_plaza_character_profiles_v7:{character:'boy'}};const db={from:table=>{const q={select:()=>q,eq:()=>q,maybeSingle:async()=>({data:tables[table]})};return q;},storage:{from:()=>({upload:async(key,buffer)=>{saved={key,buffer};return {data:{path:key}};}})}};const service=createPlazaSocialServiceV16({supabase:db,enabled:()=>true});const image=jpeg.encode({width:2,height:2,data:Buffer.alloc(16,255)},90).data;await service.upload({id:MEMBER,phone:'0900000001'},COMMAND,image);assert.equal(saved.key,MEMBER+'/'+COMMAND+'.jpg');assert.equal(jpeg.decode(saved.buffer).width,2);const broken=Buffer.from([255,216,255,192,0,11,8,0,20,0,30,1,1,17,0,255,217]);await assert.rejects(service.upload({id:MEMBER,phone:'0900000001'},COMMAND,broken),{code:'PLAZA_INVALID_AVATAR'});});
